### ISSUE TITLE
Line cropping the rest of the image

### ISSUE THREAD

**Issue by josuah** [sathibault/vgrs#5]
Using a rectangle with full size, this works:

```python
vgr2d.display2d(0, [
  vgr2d.Line(10, 390, 630, 390, 7, 10), # bottom
  vgr2d.Line(10, 10, 10, 390, 7, 10), # left
  vgr2d.Line(630, 10, 630, 390, 7, 10), # right
  vgr2d.Line(10, 10, 630, 10, 7, 10), # top
], 640, 400)
```
![mpv-shot0002](https://user-images.githubusercontent.com/55351021/232536955-d32b50fb-a9ee-4837-b45e-be272fb45c8a.jpg)

But moving the top edge down leads to this:
```python
vgr2d.display2d(0, [
  vgr2d.Line(10, 190, 630, 190, 7, 10), # bottom (shifted up)
  vgr2d.Line(10, 10, 10, 390, 7, 10), # left
  vgr2d.Line(630, 10, 630, 390, 7, 10), # right
  vgr2d.Line(10, 10, 630, 10, 7, 10), # top
], 640, 400)
```
![mpv-shot0003](https://user-images.githubusercontent.com/55351021/232537047-a4156e66-b73e-4d0d-bddb-706ac173ed98.jpg)

And changing the order the lines are printed lead to this:
```python
vgr2d.display2d(0, [
  vgr2d.Line(10, 10, 10, 390, 7, 10), # left
  vgr2d.Line(630, 10, 630, 390, 7, 10), # right
  vgr2d.Line(10, 10, 630, 10, 7, 10), # top
  vgr2d.Line(10, 190, 630, 190, 7, 10), # bottom (shifted up, printed last)
], 640, 400)
```
![mpv-shot0004](https://user-images.githubusercontent.com/55351021/232537132-a1895777-8275-4b80-8e1b-a64e05ecc380.jpg)

**Comment by sathibault** [comment]
This should be resolved in current version.

**Comment by josuah** [comment]
I confirm, thank you for the fix!
