### ISSUE TITLE
Polygon generation of "W" error

### ISSUE THREAD

**Issue by sathibault** [sathibault/vgrs#7]
This W shape polygon is only partially rendered:
[(414,217),(385,103),(416,102),(432,174),(451,102),(480,102),(498,175),(515,102),(545,103),(516,218),(483,218),(464,151),(447,219),(431,219)]
![partial-w](https://user-images.githubusercontent.com/371395/234608528-6e06ad91-a37d-4775-97e6-8ff1e67ada28.jpg)

**Comment by josuah** [comment]
Fixed by the `dev` branch!
